@isTest
public class TestF_Accounts {
    @isTest
    static void testF_Accounts(){
        // try{
        // Account obj = new Account();
        // Set Fields
        // obj = (Account) FieloPLT.SObjectService.setRequiredFields(Account.sObjectType, obj);
        // obj.March_D_affectation__c= SObjectType.Account.Fields.March_D_affectation__c.PicklistValues[0].getValue();
        // obj.Sous_Marche_D_affectation__c= SObjectType.Account.Fields.Sous_Marche_D_affectation__c.PicklistValues[7].getValue();
        // obj.Categorie__c= SObjectType.Account.Fields.Categorie__c.PicklistValues[0].getValue();
        // obj.Sous_cat_gorie__c = SObjectType.Account.Fields.Sous_cat_gorie__c.PicklistValues[0].getValue();
        // insert obj;
        // Set Fields
        // obj = (Account) FieloPLT.SObjectService.setRequiredFields(Account.sObjectType, obj);
        // obj.March_D_affectation__c= SObjectType.Account.Fields.March_D_affectation__c.PicklistValues[0].getValue();
        // obj.Sous_Marche_D_affectation__c= SObjectType.Account.Fields.Sous_Marche_D_affectation__c.PicklistValues[7].getValue();
        // obj.Categorie__c= SObjectType.Account.Fields.Categorie__c.PicklistValues[0].getValue();
        // obj.Sous_cat_gorie__c = SObjectType.Account.Fields.Sous_cat_gorie__c.PicklistValues[0].getValue();
        // update obj;
        // } catch(Exception e) {}
    }
}