@isTest
public class TestF_Lignesdecommandes {
    @isTest
    static void testF_Lignesdecommandes(){
        // try{
        // SalesLine__c obj = new SalesLine__c();
        // Set Fields
        // obj = (SalesLine__c) FieloPLT.SObjectService.setRequiredFields(SalesLine__c.sObjectType, obj);
        // insert obj;
        // Set Fields
        // obj = (SalesLine__c) FieloPLT.SObjectService.setRequiredFields(SalesLine__c.sObjectType, obj);
        // update obj;
        // } catch(Exception e) {}
    }
}